# Day 95 - association rules

1. A transactions DataFrame (transaction database) containing data in a certain grocery store is given: <br>
<br>
                   products <br>
1                bread eggs <br>
2           bread eggs milk <br>
3               milk cheese <br>
4       bread butter cheese <br>
5                 eggs milk <br>
6  bread milk butter cheese <br>
<br>
Each row contains products purchased by one customer. Split each row of the products column by a space character and extend to the DataFrame object. The object should have four columns (maximum number of products in one transaction). In the missing places put None as shown below and assign to expanded variable. <br>
In response, print the expanded variable to the console.<br>
<br>
Expected result: <br>
<br>
       0       1       2       3 <br>
1  bread    eggs    None    None <br>
2  bread    eggs    milk    None <br>
3   milk  cheese    None    None <br>
4  bread  butter  cheese    None <br>
5   eggs    milk    None    None <br> 
6  bread    milk  butter  cheese <br>

In [1]:
import numpy as np
import pandas as pd
 
 
data = {
    'products': [
        'bread eggs',
        'bread eggs milk',
        'milk cheese',
        'bread butter cheese',
        'eggs milk',
        'bread milk butter cheese',
    ]
}
 
transactions = pd.DataFrame(data=data, index=range(1, 7))
expanded = transactions['products'].str.split(expand=True)
print(expanded)

       0       1       2       3
1  bread    eggs    None    None
2  bread    eggs    milk    None
3   milk  cheese    None    None
4  bread  butter  cheese    None
5   eggs    milk    None    None
6  bread    milk  butter  cheese

2. A transactions DataFrame (transaction database) containing data in a certain grocery store is given: <br>
<br>
                   products <br>
1                bread eggs <br>
2           bread eggs milk <br>
3               milk cheese <br>
4       bread butter cheese <br>
5                 eggs milk <br>
6  bread milk butter cheese <br>
<br>
Each row contains products purchased by one customer. Each row of the products column was splitted by a space character and expanded to the following DataFrame (expanded variable) as shown below:<br>
<br>
       0       1       2       3 <br>
1  bread    eggs    None    None <br>
2  bread    eggs    milk    None <br>
3   milk  cheese    None    None <br>
4  bread  butter  cheese    None <br>
5   eggs    milk    None    None <br> 
6  bread    milk  butter  cheese <br>


The names of all products were assigned to the products variable (sorted alphabetically):<br>
<br>
['bread', 'butter', 'cheese', 'eggs', 'milk']
<br>
Use a one-hot encoding to encode transaction database as shown below and assign it to transactions_encoded_df variable. In response, print the transactions_encoded_df DataFrame to the console.<br>
<br>
Expected result: <br>
<br>
   bread  butter  cheese  eggs  milk <br>
0      1       0       0     1     0 <br>
1      1       0       0     1     1 <br>
2      0       0       1     0     1 <br> 
3      1       1       1     0     0 <br>
4      0       0       0     1     1 <br>
5      1       1       1     0     1 <br>

In [2]:
import pandas as pd
 
 
data = {
    'products': [
        'bread eggs',
        'bread eggs milk',
        'milk cheese',
        'bread butter cheese',
        'eggs milk',
        'bread milk butter cheese',
    ]
}
 
transactions = pd.DataFrame(data=data, index=range(1, 7))
expanded = transactions['products'].str.split(expand=True)
 
products = []
for col in expanded.columns:
    for product in expanded[col].unique():
        if product is not None and product not in products:
            products.append(product)
 
products.sort()
 
transactions_encoded = np.zeros(
    (len(transactions), len(products)), dtype='int8'
)
 
for row in zip(
    range(len(transactions)),
    transactions_encoded,
    expanded.values,
):
    for idx, product in enumerate(products):
        if product in row[2]:
            transactions_encoded[row[0], idx] = 1
 
transactions_encoded_df = pd.DataFrame(
    transactions_encoded, columns=products
)
print(transactions_encoded_df)

   bread  butter  cheese  eggs  milk
0      1       0       0     1     0
1      1       0       0     1     1
2      0       0       1     0     1
3      1       1       1     0     0
4      0       0       0     1     1
5      1       1       1     0     1

3. A transactions DataFrame is given: <br>
<br>
                   products <br>
1                bread eggs <br>
2           bread eggs milk <br>
3               milk cheese <br>
4       bread butter cheese <br>
5                 eggs milk <br>
6  bread milk butter cheese <br>
<br>
Each row contains products purchased by one customer. Each row of the products column was splitted by a space character and expanded to the following DataFrame (expanded variable) as shown below: <br>
<br>
       0       1       2       3 <br>
1  bread    eggs    None    None <br>
2  bread    eggs    milk    None <br>
3   milk  cheese    None    None <br>
4  bread  butter  cheese    None <br>
5   eggs    milk    None    None <br>
6  bread    milk  butter  cheese <br>
<br>
The names of all products were assigned to the products variable (sorted alphabetically): <br>
<br>
['bread', 'butter', 'cheese', 'eggs', 'milk'] <br>
<br>
One-hot encoding was used to encode the transaction database (transactions_encoded_df variable): <br>
<br>
   bread  butter  cheese  eggs  milk <br>
0      1       0       0     1     0 <br> 
1      1       0       0     1     1 <br>
2      0       0       1     0     1 <br>
3      1       1       1     0     0 <br>
4      0       0       0     1     1 <br>
5      1       1       1     0     1 <br>
Calculate the support for pairs: (butter, bread) and (butter, milk). In response, print the result to the console as shown below (round the support to four decimal places). <br>
Tip: support(product A, product B) = number of transactions containing product A and product B / total number of transactions in the database <br>
<br>
Expected result: <br>
<br>
support(butter, bread) = 0.3333 <br>
support(butter, milk) = 0.1667

In [3]:
import numpy as np
import pandas as pd
 
data = {
    'products': [
        'bread eggs',
        'bread eggs milk',
        'milk cheese',
        'bread butter cheese',
        'eggs milk',
        'bread milk butter cheese',
    ]
}
 
transactions = pd.DataFrame(data=data, index=range(1, 7))
expanded = transactions['products'].str.split(expand=True)
 
products = []
for col in expanded.columns:
    for product in expanded[col].unique():
        if product is not None and product not in products:
            products.append(product)
products.sort()
 
transactions_encoded = np.zeros(
    (len(transactions), len(products)), dtype='int8'
)
 
for row in zip(
    range(len(transactions)),
    transactions_encoded,
    expanded.values,
):
    for idx, product in enumerate(products):
        if product in row[2]:
            transactions_encoded[row[0], idx] = 1
 
transactions_encoded_df = pd.DataFrame(
    transactions_encoded, columns=products
)
 
sup_butter_bread = len(
    transactions_encoded_df.query("butter == 1 and bread == 1")
) / len(transactions_encoded_df)
sup_butter_milk = len(
    transactions_encoded_df.query("butter == 1 and milk == 1")
) / len(transactions_encoded_df)
 
print(f'support(butter, bread) = {sup_butter_bread:.4f}')
print(f'support(butter, milk) = {sup_butter_milk:.4f}')

support(butter, bread) = 0.3333
support(butter, milk) = 0.1667